name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            # 0. 환경 변수 로드
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 1. 프로젝트 폴더로 이동
            cd ~/var/www/frontend

            # 2. 최신 코드 가져오기
            git pull origin main

            # 3. 패키지 설치 및 빌드
            npm install
            npm run build

            # 4. PM2로 서버 재시작
            pm2 restart frontend || pm2 start npm --name "frontend" -- start

            echo "배포 완료됨"
